import { readFileSync, writeFileSync, mkdirSync } from 'node:fs';
import { dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';
import { extensionId } from './extension-id.mjs';
import { SHORTCUT_HOSTS } from '../src/resolve.js';
import { BRIDGE_PROTOCOL_VERSION, BRIDGE_HOST } from '../src/bridge-protocol.js';

const root = resolve(dirname(fileURLToPath(import.meta.url)), '..');
export function generatedConfig(manifest) {
  const id = extensionId(Buffer.from(manifest.key, 'base64'));
  const rules = SHORTCUT_HOSTS.map((host, i) => ({
    id: i + 1,
    priority: 1,
    action: {
      type: 'redirect',
      redirect: { regexSubstitution: `chrome-extension://${id}/src/resolve.html?shortcut=\\0` },
    },
    condition: {
      regexFilter: `^https?://${host.replaceAll('.', '\\.')}(:[0-9]+)?/.*$`,
      resourceTypes: ['main_frame'],
      isUrlFilterCaseSensitive: false,
    },
  }));
  return {
    'rules/shortcuts.json': JSON.stringify(rules, null, 2) + '\n',
    'macos/Sources/PullDeckKit/BuildIdentity.swift': `// Generated by tools/generate-config.mjs.\npublic enum BuildIdentity {\n    public static let extensionID = "${id}"\n    public static let version = "${manifest.version}"\n    public static let protocolVersion = ${BRIDGE_PROTOCOL_VERSION}\n    public static let hostName = "${BRIDGE_HOST}"\n}\n`,
  };
}
export function generateConfig({ check = false } = {}) {
  const manifest = JSON.parse(readFileSync(resolve(root, 'manifest.json'), 'utf8'));
  for (const [path, contents] of Object.entries(generatedConfig(manifest))) {
    const full = resolve(root, path);
    if (check) {
      let actual;
      try {
        actual = readFileSync(full, 'utf8');
      } catch {
        /* missing generated file */
      }
      if (actual !== contents) throw Error(`${path} is stale. Run npm run generate.`);
    } else {
      mkdirSync(dirname(full), { recursive: true });
      writeFileSync(full, contents);
    }
  }
}
if (process.argv[1] && resolve(process.argv[1]) === fileURLToPath(import.meta.url))
  generateConfig({ check: process.argv.includes('--check') });
